//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_ciudad
{
    using System;
    using System.Collections.Generic;
    
    public partial class reclamos
    {
        public int Reclamos1 { get; set; }
        public string usuario { get; set; }
        public string direccion { get; set; }
        public string fecha { get; set; }
        public string descripcion { get; set; }
        public byte[] foto { get; set; }
    }
}
