//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamarque_web.Models
{
    using DHTMLX.Scheduler;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class eventos_bd
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DHXJson(Alias = "id")]
        public int Id { get; set; }

        [DHXJson(Alias = "text")]
        public string descripcion { get; set; }

        [DHXJson(Alias = "start_date")]
        public Nullable<System.DateTime> startDate { get; set; }

        [DHXJson(Alias = "end_date")]
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
