//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamarque_ciudad
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain_bd
    {
        public string user { get; set; }
        public byte[] photo { get; set; }
        public string adr { get; set; }
        public string desc { get; set; }
        public System.DateTime day { get; set; }
    }
}
