//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamarque_ciudad
{
    using System;
    using System.Collections.Generic;
    
    public partial class map
    {
        public string name { get; set; }
        public int lat { get; set; }
        public int leng { get; set; }
        public string desc { get; set; }
    }
}
