
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lamarque_ciudad
{

using System;
    using System.Collections.Generic;
    
public partial class people_bd
{

    public string user { get; set; }

    public string pass { get; set; }

    public string name { get; set; }

    public string lastName { get; set; }

    public System.DateTime birth { get; set; }

    public string mail { get; set; }

    public int id { get; set; }

}

}
