//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamarque_ciudad
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_bd
    {
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime nacimiento { get; set; }
        public string correo { get; set; }
        public int id { get; set; }
    }
}
