//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamarque_ciudad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A2A1B8_netbd1Entities2 : DbContext
    {
        public DB_A2A1B8_netbd1Entities2()
            : base("name=DB_A2A1B8_netbd1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contacto_bd> contacto_bd { get; set; }
        public virtual DbSet<eventos_bd> eventos_bd { get; set; }
        public virtual DbSet<servicios_bd> servicios_bd { get; set; }
        public virtual DbSet<usuarios_bd> usuarios_bd { get; set; }
    }
}
